[colors.primary]
background = '#19120d'
foreground = '#f0dfd6'
 
[colors.cursor]
text = '#f0dfd6'
cursor = '#d7c3b7' 
 
[colors.vi_mode_cursor]
text = '#19120d'
cursor = '#ffb785' 
 
[colors.search.matches]
foreground = '#52443b' 
background = '#c8ca94' 
 
[colors.search.focused_match]
foreground = '#52443b' 
background = '#ffb785' 
 
[colors.footer_bar]
foreground = '#52443b' 
background = '#f0dfd6' 
 
[colors.hints.start]
foreground = '#52443b' 
background = '#e4bfa8' 
 
[colors.hints.end]
foreground = '#52443b' 
background = '#e4bfa8' 
 
[colors.selection]
text = '#19120d'
background = '#ffb785'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#ffb785' 
yellow = '#8a5022' 
blue = '#ffb785' 
magenta = '#c8ca94' 
cyan = '#e4bfa8' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 

